version: '3.3'

services:

  #Start pega backend DB
  postgresql-pega-backend:

    container_name: postgresql-pega
    
    build:
      dockerfile: Dockerfile
      context: ./Postgresql-BackendDB
    
    ports:
      - 5432:5432
    
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # substitute with db password
      - POSTGRES_USER=${POSTGRES_USER}  # substitute with db user
      - POSTGRES_DB=${POSTGRES_DB}  # substitute with db name

    volumes:
      - ${PEGA_DUMP}:/resources/  #substitue ${PEGA_DUMP} with directory holding pega.dump file

  #Start pega prweb 
  pega-prpc-pe:
    
    container_name: pega

    build:
      dockerfile: Dockerfile
      context: ./PegaPRPC-WebApp

    environment:
      - JDBC_URL=jdbc:postgresql://postgresql-pega-backend/${POSTGRES_DB}   #replace this with your postgresql installation ip
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=5432
      - JDBC_CLASS=org.postgresql.Driver

    volumes:
      - ${PEGA_DUMP}:/resources/  #substitue ${PEGA_DUMP} with directory holding pega.dump file
      
    ports:
      - 9090:8080 #regular PegaPE is on 9090 port

    # this makes sure that pega backend is running before pega prpc is launched
    depends_on:
     - postgresql-pega-backend